@extends('layouts.master')
@section('content')
  @include('main.carousel')
  @include('main.modal')
@stop
@push('scripts')
<script>
  $(document).ready(function(){
    $('#myModal').modal('show');
  });
</script>
@endpush